"""Lazy, thread-safe reader for the bundled dogma table (``fit_dogma.json.gz``).

The table is a filtered slice of CCP's SDE -- the attributes, effects, dbuffs
and per-type attribute values the fit simulator needs -- generated by
``tools/gen_fit_dogma.py``.  This module is the ONLY thing that knows the wire
encoding; every consumer goes through the typed accessors below.

Layering (imports flow only downward)::

    dogma_data <- fit_sim <- fit_sim_links <- fit_sim_stats <- {panel, fleet_stats}

so this module imports the standard library and ``app_path`` only: no Tk, no
``requests``, no ``numpy``, no ``fc_gui``.

**Nothing loads at startup.**  :func:`load` is called explicitly, from worker
threads, on first use.  The accessors deliberately do NOT auto-load: an accessor
call before a successful :func:`load` raises :class:`DogmaUnavailable` rather
than silently paying a decode on whatever thread happened to ask.  That keeps
the "no dogma work on the Tk thread" guarantee checkable.

Failure is never an exception: a missing file, a corrupt gzip, unparseable JSON
or a misshaped table all leave the module unloaded and make :func:`load` return
``False``; callers degrade to "stats unavailable".  A failed load may be retried
(``_loaded`` stays ``False``), so a table dropped in later is picked up.

Wire encoding (compact separators, gzip level 9; ids are JSON object keys and so
arrive as strings)::

    {"v": <sde build>,
     "attrs":   {"<id>": [default, stackable01, highIsGood01]},
     "types":   {"<id>": {"a": [attr_id, value, ...], "e": [effect_id, ...],
                          "g": group_id, "c": category_id}},
     "effects": {"<id>": {"cat": n,
                          "m": [[domain, func, modifiedAttr, modifyingAttr,
                                 op, skillTypeID|null, groupID|null], ...]}},
     "dbuffs":  {"<id>": {"agg": "Maximum", "op": 6,
                          "m": [[kind, attr, groupID|null, skillTypeID|null], ...]}},
     "skills":  [type_id, ...]}

A type's ``a`` list is a FLAT id/value sequence and carries only the attributes
whose value differs from the attribute default, so :func:`type_attrs` returns
the type's OWN values only -- defaults are supplied on read via
``attr_info(attr_id).default`` (the engine's ``attr(item, id)`` does the fill).

Module-level state is exactly ``_table``, ``_loaded``, ``_lock`` and the one
bounded LRU (``_type_cache``, 256 entries).  No append-only containers.
"""

import functools
import gzip
import json
import threading
from typing import NamedTuple

from app_path import resolve_data_file

DATA_FILE = "fit_dogma.json.gz"

#: Per-type attribute LRU bound (see :func:`type_attrs`).
_TYPE_CACHE_SIZE = 256

#: Unknown attribute ids answer with this rather than raising -- an attribute the
#: filter dropped is one nothing in the kept set modifies, so "0.0, stackable,
#: higher-is-better" is the harmless neutral reading.
_UNKNOWN_ATTR_DEFAULT = (0.0, True, True)


class DogmaUnavailable(RuntimeError):
    """Raised by every accessor when no table is loaded."""


class Modifier(NamedTuple):
    """One ``modifierInfo`` entry off an effect."""
    domain: str                  # "shipID" | "charID" | "otherID" | "targetID" | "structureID"
    func: str                    # "ItemModifier" | "LocationModifier" | "LocationGroupModifier"
                                 # | "LocationRequiredSkillModifier" | "OwnerRequiredSkillModifier"
    modified_attr: int
    modifying_attr: int
    operation: int               # dogma op code (-1 preAssign ... 7 postAssign)
    skill_type_id: int | None
    group_id: int | None


class EffectDef(NamedTuple):
    effect_id: int
    category: int                # effectCategoryID (0 passive, 1 active, 2 target, 4 online, 5 overload)
    modifiers: tuple[Modifier, ...]


class AttrInfo(NamedTuple):
    default: float
    stackable: bool
    high_is_good: bool


class BuffModifier(NamedTuple):
    kind: str                    # "item" | "location" | "location_group" | "location_skill"
    attr: int
    group_id: int | None
    skill_type_id: int | None


class DbuffDef(NamedTuple):
    buff_id: int
    aggregate: str               # "Maximum" | "Minimum"
    operation: int               # the op code the buff applies with; NOT always postPercent --
                                  # consumers must honour it
    modifiers: tuple[BuffModifier, ...]


# --------------------------------------------------------------------------
# module state
# --------------------------------------------------------------------------

_table: dict | None = None
_loaded = False
_lock = threading.Lock()


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------

def _data_path() -> str | None:
    """The shipped table's path, or None when it is not present.

    ``prefer="bundle"``: this is a PRISTINE generated table that must always
    read the packaged copy and never be shadowed by a stray file in the
    writable dir (the ``fit_types.json`` / ``inv_groups`` rule)."""
    return resolve_data_file(DATA_FILE, prefer="bundle")


def _decode(path: str) -> dict:
    """Read + gunzip + parse. Raises on any I/O or JSON problem; :func:`load`
    is the layer that turns that into ``False``. Split out so the load-once
    contract can be spied on in tests."""
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        return json.load(fh)


_SECTIONS = (("attrs", dict), ("types", dict), ("effects", dict),
             ("dbuffs", dict), ("skills", (list, tuple)))


def _shape_error(table) -> str | None:
    """None when ``table`` is a well-shaped top level, else why it is not.

    Only the TOP level is checked -- deep validation of every row would cost a
    full walk of the table on every load for a defect only the generator (and
    its own tests) can introduce."""
    if not isinstance(table, dict):
        return f"top level is {type(table).__name__}, expected object"
    build = table.get("v")
    if not isinstance(build, int) or isinstance(build, bool):
        return f"'v' (sde build) is {build!r}, expected int"
    for name, kinds in _SECTIONS:
        if name not in table:
            return f"missing section {name!r}"
        if not isinstance(table[name], kinds):
            return f"section {name!r} is {type(table[name]).__name__}"
    return None


def _install(table: dict) -> None:
    """Adopt ``table`` as the live one. Callers hold ``_lock`` or own the module
    (the test seams)."""
    global _table, _loaded
    _table = table
    _loaded = True
    _type_cache.cache_clear()


def load() -> bool:
    """Load the bundled table if it is not already loaded. Returns whether a
    table is available afterwards.

    Idempotent and lock-guarded: concurrent first callers decode exactly once.
    Never raises -- a missing file, corrupt gzip, bad JSON or misshaped table
    return ``False`` and leave the module unloaded (so a later call retries).

    Call from a WORKER thread only; it reads and parses a multi-megabyte file.
    """
    global _table, _loaded
    if _loaded:
        return True
    with _lock:
        if _loaded:
            return True
        path = _data_path()
        if not path:
            print(f"[Dogma] {DATA_FILE} not found; fit stats unavailable")
            return False
        try:
            table = _decode(path)
        except Exception as exc:          # missing/corrupt/unparseable: degrade
            print(f"[Dogma] Failed to read {path}: {exc}")
            return False
        problem = _shape_error(table)
        if problem:
            print(f"[Dogma] Ignoring {path}: {problem}")
            return False
        _install(table)
        print(f"[Dogma] Loaded {len(table['types'])} types "
              f"(SDE build {table['v']}) from {DATA_FILE}")
        return True


def is_loaded() -> bool:
    """True once a table has been installed. Never raises."""
    return _loaded


# --------------------------------------------------------------------------
# accessors
# --------------------------------------------------------------------------

def _require() -> dict:
    if not _loaded or _table is None:
        raise DogmaUnavailable(
            f"{DATA_FILE} is not loaded -- call dogma_data.load() from a worker "
            "thread and honour a False result")
    return _table


def _row(section: str, key: int):
    """One record out of ``section``, or None. Ids are JSON object keys (str);
    the int fallback lets hand-built test tables use int keys."""
    rows = _require()[section]
    row = rows.get(str(key))
    if row is None:
        row = rows.get(key)
    return row


def _type_row(type_id: int) -> dict:
    row = _row("types", type_id)
    if row is None:
        raise KeyError(type_id)
    return row


def sde_build() -> int:
    """The SDE build the table was generated from."""
    return int(_require()["v"])


def has_type(type_id: int) -> bool:
    """Whether the table models this type. The probe callers use before the
    ``type_*`` accessors, which raise ``KeyError`` for unknown ids so the engine
    can record them as unmodeled."""
    return _row("types", type_id) is not None


@functools.lru_cache(maxsize=_TYPE_CACHE_SIZE)
def _type_attrs_pairs(type_id: int) -> tuple[tuple[int, float], ...]:
    """The type's own (attr_id, value) pairs, immutable and cached.

    ``a`` is a flat id/value sequence and so must have an even length; the
    generator can never emit an odd one, so an odd length here is a
    corruption signal, not a degrade path -- raise rather than silently drop
    the dangling id or misread it as the next pair's id."""
    flat = _type_row(type_id).get("a") or ()
    if len(flat) % 2:
        raise ValueError(f"type {type_id}: odd attribute list")
    return tuple((int(flat[i]), float(flat[i + 1])) for i in range(0, len(flat), 2))


#: The one bounded cache this module owns. Cleared on every (re)install.
_type_cache = _type_attrs_pairs


def type_attrs(type_id: int) -> dict[int, float]:
    """``{attr_id: value}`` of the type's OWN attribute values -- a NEW dict on
    every call, which the caller owns and may mutate (the engine mutates it).

    Only attributes whose value differs from the attribute default are stored,
    so an attribute absent here reads as ``attr_info(attr_id).default``.
    Raises ``KeyError`` for an unknown type (probe with :func:`has_type`)."""
    return dict(_type_attrs_pairs(type_id))


def type_effects(type_id: int) -> tuple[int, ...]:
    """Effect ids on the type. ``KeyError`` for an unknown type."""
    return tuple(int(e) for e in (_type_row(type_id).get("e") or ()))


def type_group(type_id: int) -> int:
    """groupID. ``KeyError`` for an unknown type."""
    return int(_type_row(type_id)["g"])


def type_category(type_id: int) -> int:
    """categoryID. ``KeyError`` for an unknown type."""
    return int(_type_row(type_id)["c"])


def effect(effect_id: int) -> EffectDef | None:
    """The effect, or None when the table does not carry it."""
    row = _row("effects", effect_id)
    if row is None:
        return None
    return EffectDef(
        effect_id=int(effect_id),
        category=int(row["cat"]),
        modifiers=tuple(_modifier(m) for m in (row.get("m") or ())),
    )


def _modifier(row) -> Modifier:
    domain, func, modified, modifying, op, skill_id, group_id = row
    return Modifier(
        domain=str(domain),
        func=str(func),
        modified_attr=int(modified),
        modifying_attr=int(modifying),
        operation=int(op),
        skill_type_id=None if skill_id is None else int(skill_id),
        group_id=None if group_id is None else int(group_id),
    )


def attr_info(attr_id: int) -> AttrInfo:
    """Default / stackability / polarity for an attribute. An unknown id answers
    ``AttrInfo(0.0, True, True)`` rather than raising -- see
    ``_UNKNOWN_ATTR_DEFAULT``."""
    row = _row("attrs", attr_id)
    if row is None:
        return AttrInfo(*_UNKNOWN_ATTR_DEFAULT)
    default, stackable, high_is_good = row
    return AttrInfo(float(default), bool(stackable), bool(high_is_good))


def dbuff(buff_id: int) -> DbuffDef | None:
    """The warfare-buff definition, or None when the table does not carry it."""
    row = _row("dbuffs", buff_id)
    if row is None:
        return None
    return DbuffDef(
        buff_id=int(buff_id),
        aggregate=str(row["agg"]),
        operation=int(row["op"]),
        modifiers=tuple(_buff_modifier(m) for m in (row.get("m") or ())),
    )


def _buff_modifier(row) -> BuffModifier:
    kind, attr, group_id, skill_id = row
    return BuffModifier(
        kind=str(kind),
        attr=int(attr),
        group_id=None if group_id is None else int(group_id),
        skill_type_id=None if skill_id is None else int(skill_id),
    )


def skill_type_ids() -> tuple[int, ...]:
    """Every skill type id the table kept (category 16). The engine gives each
    one an item at the All-V level."""
    return tuple(int(t) for t in _require()["skills"])


# --------------------------------------------------------------------------
# test seams -- tests SELF-SEED rather than reading the shipped table
# --------------------------------------------------------------------------

def _seed_for_tests(table: dict) -> None:
    """Install ``table`` as if it had been loaded from disk.

    Validates the top-level shape exactly as :func:`load` does, but RAISES
    ``ValueError`` instead of degrading -- a test that hands over a misshaped
    table has a bug, and a silent no-op would false-pass."""
    problem = _shape_error(table)
    if problem:
        raise ValueError(f"misshaped dogma table: {problem}")
    with _lock:
        _install(table)


def _reset_for_tests() -> None:
    """Return the module to its pristine unloaded state (and drop the LRU), so
    no test can leave a fixture table poisoning the rest of the process."""
    global _table, _loaded
    with _lock:
        _table = None
        _loaded = False
        _type_cache.cache_clear()
