# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['fc_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('fire_alert.mp3', '.'),
        ('stargate_jumps.json', '.'),
        ('system_coords.json', '.'),
        ('fit_types.json', '.'),
        ('assets/bursts/shield.png', 'assets/bursts'),
        ('assets/bursts/armor.png', 'assets/bursts'),
        ('assets/bursts/skirmish.png', 'assets/bursts'),
        ('assets/bursts/info.png', 'assets/bursts'),
        ('assets/bursts/shield_21.png', 'assets/bursts'),
        ('assets/bursts/armor_21.png', 'assets/bursts'),
        ('assets/bursts/skirmish_21.png', 'assets/bursts'),
        ('assets/bursts/info_21.png', 'assets/bursts'),
        ('assets/tts/fleet_lost_10.mp3', 'assets/tts'),
        ('assets/tts/fleet_lost_25.mp3', 'assets/tts'),
        ('assets/tts/fleet_lost_50.mp3', 'assets/tts'),
        ('assets/tts/decloaked.mp3', 'assets/tts'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FCTool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='NONE',
    manifest='fctool.manifest',
)
