"""
Local New Eden coordinate / name / legality table.

Loads system_coords.json (bundled with the app, generated by
tools/gen_system_coords.py) once into memory. Replaces per-system ESI
position/name lookups in the jump-range hot path with pure local reads.
"""
import json
import os
import threading

from app_path import resolve_data_file

_COORDS_FILENAME = "system_coords.json"
_JUMPS_FILENAME = "stargate_jumps.json"

# In-memory tables, built once by _load().
_coords: dict[int, tuple[float, float, float]] = {}   # id -> (x, y, z) meters
_region_of: dict[int, int] = {}                        # id -> region_id
_security_of: dict[int, float] = {}                    # id -> true-sec (full precision)
_name_of: dict[int, str] = {}                          # id -> canonical name
_id_of_name: dict[str, int] = {}                       # lowercased name -> id
_loaded = False
_lock = threading.Lock()

# Region adjacency, built lazily by _load_region_adjacency() from the bundled
# stargate table. Its own flag/lock: most callers never ask for it, so the join
# is only paid for on demand, and it must not serialize behind _load()'s lock.
_region_adj: dict[int, set[int]] = {}                  # region_id -> {region_id}
_region_adj_loaded = False
_region_adj_lock = threading.Lock()

# --- Jump-drive legality (verified IDs; see plan) ----------------------------
EXCLUDED_REGION_IDS = {
    10000070,   # Pochven       -- jump drives can exit but not enter
    10000004,   # UUA-F4 (Jove) -- inaccessible
    10000017,   # J7HZ-F (Jove) -- inaccessible
    10000019,   # A821-A (Jove) -- inaccessible
    10001000,   # Yasna Zakh    -- Zarzakh's region; cyno beacon blocked
}
ZARZAKH_SYSTEM_ID = 30100000   # true-sec -1.00, so exclude by ID not security
HIGHSEC_CUTOFF = 0.45          # true_security >= 0.45 is highsec (cyno blocked)


def _data_path() -> str | None:
    """Prefer a writable copy next to the exe, else the bundled read-only copy
    (``prefer="writable"``); None when neither exists so callers fall back to ESI."""
    return resolve_data_file(_COORDS_FILENAME, prefer="writable")


def _load() -> None:
    global _loaded
    if _loaded:
        return
    with _lock:
        if _loaded:
            return
        path = _data_path()
        if not path:
            # No table shipped/cached: degrade gracefully -- callers fall back to ESI.
            _loaded = True
            return
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw = json.load(f)
            for sid_str, rec in raw.items():
                sid = int(sid_str)
                _coords[sid] = (rec["x"], rec["y"], rec["z"])
                _region_of[sid] = rec["region_id"]
                _security_of[sid] = rec["security"]
                name = rec["name"]
                _name_of[sid] = name
                _id_of_name[name.lower()] = sid
            print(f"[Coords] Loaded {len(_coords)} systems from {os.path.basename(path)}")
        except Exception as e:  # corrupt/partial file: degrade, don't crash the app
            print(f"[Coords] Failed to load {path}: {e}")
        _loaded = True


def get_position(system_id: int) -> dict | None:
    """Return {"x","y","z"} (ESI-compatible shape) or None if not in the table."""
    _load()
    xyz = _coords.get(system_id)
    if xyz is None:
        return None
    return {"x": xyz[0], "y": xyz[1], "z": xyz[2]}


def resolve_name(name: str) -> int | None:
    """Exact (case-insensitive) name -> system_id, or None. No fuzzy matching."""
    _load()
    return _id_of_name.get(name.lower())


def get_name(system_id: int) -> str | None:
    """Return the canonical system name from the bundled table, or None.

    The reverse of `resolve_name`, and the local/offline alternative to
    `zkill_monitor.resolve_name(sid, "solar_system")` / `jump_range.
    get_system_info`, both of which do a rate-limited HTTP GET on a cache miss.
    That matters wherever a name is needed ON THE TK THREAD (the battle
    ledger's per-second render is the current caller): a pure in-memory read
    cannot stall the UI. None for J-space or when no table shipped — callers
    fall back to str(id) or to ESI."""
    _load()
    return _name_of.get(system_id)


def get_region_id(system_id: int) -> int | None:
    """Return the region_id for a system from the bundled table, or None when the
    system isn't in the table (e.g. J-space wormholes, or no table shipped).

    Lets callers resolve a staging system's region locally/instantly instead of
    the ESI systems->constellation->region traversal."""
    _load()
    return _region_of.get(system_id)


def get_security(system_id: int) -> float | None:
    """Return the full-precision true-sec for a system from the bundled table,
    or None when the system isn't in the table (e.g. J-space wormholes, or no
    table shipped)."""
    _load()
    return _security_of.get(system_id)


def get_kspace_name_to_id() -> dict[str, int]:
    """{canonical_name: system_id} for every K-space system in the bundled table.

    Seeds the autocomplete name list instantly (offline / fresh install / ESI
    down) instead of waiting on the ESI download. K-space = ids 30000000..30999999
    (excludes J-space wormholes, matching the ESI-download behavior)."""
    _load()
    return {name: sid for sid, name in _name_of.items()
            if 30_000_000 <= sid <= 30_999_999}


def is_legal_jump_destination(system_id: int) -> bool:
    """True iff a capital/JF/Black-Ops jump can land here: K-space, not Zarzakh,
    not Pochven/Jove, and lowsec/nullsec (true-sec < 0.45). Cyno-jammers are
    dynamic state and not considered here."""
    _load()
    if not (30_000_000 <= system_id <= 30_999_999):
        return False
    if system_id == ZARZAKH_SYSTEM_ID:
        return False
    region = _region_of.get(system_id)
    if region is None or region in EXCLUDED_REGION_IDS:
        return False
    sec = _security_of.get(system_id)
    if sec is None or sec >= HIGHSEC_CUTOFF:
        return False
    return True


def systems_within_range(origin_id: int, range_ly: float,
                         legal_only: bool = True) -> list[tuple[int, float]]:
    """All systems within range_ly of origin_id, as (system_id, distance_ly),
    sorted nearest-first. O(n) over the ~5,500 K-space systems -- a few ms,
    pure stdlib. Compares squared distance to avoid sqrt on non-matches."""
    from jump_range import LY_IN_METERS  # lazy import avoids a circular import
    _load()
    origin = _coords.get(origin_id)
    if origin is None:
        return []
    ox, oy, oz = origin
    max_m = range_ly * LY_IN_METERS
    max_m_sq = max_m * max_m

    out: list[tuple[int, float]] = []
    for sid, (x, y, z) in _coords.items():
        if sid == origin_id:
            continue
        dx = ox - x
        dy = oy - y
        dz = oz - z
        d_sq = dx * dx + dy * dy + dz * dz
        if d_sq > max_m_sq:
            continue
        if legal_only and not is_legal_jump_destination(sid):
            continue
        out.append((sid, (d_sq ** 0.5) / LY_IN_METERS))
    out.sort(key=lambda t: t[1])
    return out


# --- Offline region adjacency ------------------------------------------------
# stargate_jumps.json ({system_id_str: [neighbour_ids]}, bundled with the app)
# carries no region information, so gate edges are joined through _region_of:
# an edge whose two endpoints sit in different regions makes those regions
# neighbours. Pure local read -- no ESI, no network. Read directly rather than
# through jump_range: this module is deliberately project-import-free apart
# from app_path (jump_range imports requests and does HTTP).


def _load_region_adjacency() -> None:
    """Build the region -> {gate-adjacent regions} table once, lazily.

    A missing or unreadable stargate table leaves the adjacency EMPTY, so every
    lookup simply answers "no neighbours". It never raises: callers of an
    offline convenience helper must not have to guard a packaging accident."""
    global _region_adj_loaded
    if _region_adj_loaded:
        return
    # Region table first, and OUTSIDE our lock -- _load() takes _lock, and
    # taking them in a fixed order here keeps the two independent.
    _load()
    with _region_adj_lock:
        if _region_adj_loaded:
            return
        path = resolve_data_file(_JUMPS_FILENAME, prefer="writable")
        if path:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    raw = json.load(f)
                for sid_str, neighbours in raw.items():
                    a = _region_of.get(int(sid_str))
                    if a is None:
                        continue          # J-space / absent from the coord table
                    for nid in neighbours:
                        b = _region_of.get(int(nid))
                        if b is None or b == a:
                            continue
                        # Recorded in BOTH directions: the SDE lists each edge
                        # twice, but a one-sided edge must not yield a one-sided
                        # adjacency (neighbourliness is symmetric).
                        _region_adj.setdefault(a, set()).add(b)
                        _region_adj.setdefault(b, set()).add(a)
            except Exception as e:  # corrupt/partial file: degrade, don't crash
                _region_adj.clear()     # half a graph is worse than none
                print(f"[Coords] Failed to load {path}: {e}")
        _region_adj_loaded = True


def region_neighbours(region_id: int) -> set[int]:
    """Regions reachable from ``region_id`` over a single stargate, as a NEW set
    (callers may mutate it; the cached table is never handed out).

    Jump-drive-excluded regions (Pochven, the Jove regions, Zarzakh's Yasna
    Zakh) are filtered out of the RESULT -- they are never sane to propose.
    Asking ABOUT an excluded region still works and returns its real
    neighbours. Empty for an unknown region, or when no stargate table
    shipped."""
    _load_region_adjacency()
    return {r for r in _region_adj.get(region_id, ())
            if r not in EXCLUDED_REGION_IDS}


def default_scan_regions(staging_name: str) -> list[int]:
    """``[staging's region] + sorted(gate-adjacent regions)`` for a staging
    system NAME -- the default region scope for a staging-centred scan.

    Returns [] (never raises) when the name is blank, doesn't resolve, or the
    system carries no region (J-space, or no table shipped).

    The staging's OWN region is kept even when it is in EXCLUDED_REGION_IDS:
    scanning where you actually live is always sane, and that list is about
    jump-drive legality, not about what is worth looking at. Only the
    NEIGHBOURS are filtered."""
    if not isinstance(staging_name, str) or not staging_name.strip():
        return []
    sid = resolve_name(staging_name.strip())
    if sid is None:
        return []
    region = get_region_id(sid)
    if region is None:
        return []
    neighbours = region_neighbours(region)
    neighbours.discard(region)          # defensive: self-edges are skipped above
    return [region] + sorted(neighbours)
