"""
Local New Eden coordinate / name / legality table.

Loads system_coords.json (bundled with the app, generated by
tools/gen_system_coords.py) once into memory. Replaces per-system ESI
position/name lookups in the jump-range hot path with pure local reads.
"""
import json
import os
import threading

from app_path import app_dir, bundle_dir

_COORDS_FILENAME = "system_coords.json"

# In-memory tables, built once by _load().
_coords: dict[int, tuple[float, float, float]] = {}   # id -> (x, y, z) meters
_region_of: dict[int, int] = {}                        # id -> region_id
_security_of: dict[int, float] = {}                    # id -> true-sec (full precision)
_name_of: dict[int, str] = {}                          # id -> canonical name
_id_of_name: dict[str, int] = {}                       # lowercased name -> id
_loaded = False
_lock = threading.Lock()

# --- Jump-drive legality (verified IDs; see plan) ----------------------------
EXCLUDED_REGION_IDS = {
    10000070,   # Pochven       -- jump drives can exit but not enter
    10000004,   # UUA-F4 (Jove) -- inaccessible
    10000017,   # J7HZ-F (Jove) -- inaccessible
    10000019,   # A821-A (Jove) -- inaccessible
    10001000,   # Yasna Zakh    -- Zarzakh's region; cyno beacon blocked
}
ZARZAKH_SYSTEM_ID = 30100000   # true-sec -1.00, so exclude by ID not security
HIGHSEC_CUTOFF = 0.45          # true_security >= 0.45 is highsec (cyno blocked)


def _data_path() -> str | None:
    """Prefer a writable copy next to the exe, else the bundled read-only copy."""
    p = os.path.join(app_dir(), _COORDS_FILENAME)
    if os.path.exists(p):
        return p
    p = os.path.join(bundle_dir(), _COORDS_FILENAME)
    if os.path.exists(p):
        return p
    return None


def _load() -> None:
    global _loaded
    if _loaded:
        return
    with _lock:
        if _loaded:
            return
        path = _data_path()
        if not path:
            # No table shipped/cached: degrade gracefully -- callers fall back to ESI.
            _loaded = True
            return
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw = json.load(f)
            for sid_str, rec in raw.items():
                sid = int(sid_str)
                _coords[sid] = (rec["x"], rec["y"], rec["z"])
                _region_of[sid] = rec["region_id"]
                _security_of[sid] = rec["security"]
                name = rec["name"]
                _name_of[sid] = name
                _id_of_name[name.lower()] = sid
            print(f"[Coords] Loaded {len(_coords)} systems from {os.path.basename(path)}")
        except Exception as e:  # corrupt/partial file: degrade, don't crash the app
            print(f"[Coords] Failed to load {path}: {e}")
        _loaded = True


def get_position(system_id: int) -> dict | None:
    """Return {"x","y","z"} (ESI-compatible shape) or None if not in the table."""
    _load()
    xyz = _coords.get(system_id)
    if xyz is None:
        return None
    return {"x": xyz[0], "y": xyz[1], "z": xyz[2]}


def resolve_name(name: str) -> int | None:
    """Exact (case-insensitive) name -> system_id, or None. No fuzzy matching."""
    _load()
    return _id_of_name.get(name.lower())


def is_legal_jump_destination(system_id: int) -> bool:
    """True iff a capital/JF/Black-Ops jump can land here: K-space, not Zarzakh,
    not Pochven/Jove, and lowsec/nullsec (true-sec < 0.45). Cyno-jammers are
    dynamic state and not considered here."""
    _load()
    if not (30_000_000 <= system_id <= 30_999_999):
        return False
    if system_id == ZARZAKH_SYSTEM_ID:
        return False
    region = _region_of.get(system_id)
    if region is None or region in EXCLUDED_REGION_IDS:
        return False
    sec = _security_of.get(system_id)
    if sec is None or sec >= HIGHSEC_CUTOFF:
        return False
    return True


def systems_within_range(origin_id: int, range_ly: float,
                         legal_only: bool = True) -> list[tuple[int, float]]:
    """All systems within range_ly of origin_id, as (system_id, distance_ly),
    sorted nearest-first. O(n) over the ~5,500 K-space systems -- a few ms,
    pure stdlib. Compares squared distance to avoid sqrt on non-matches."""
    from jump_range import LY_IN_METERS  # lazy import avoids a circular import
    _load()
    origin = _coords.get(origin_id)
    if origin is None:
        return []
    ox, oy, oz = origin
    max_m = range_ly * LY_IN_METERS
    max_m_sq = max_m * max_m

    out: list[tuple[int, float]] = []
    for sid, (x, y, z) in _coords.items():
        if sid == origin_id:
            continue
        dx = ox - x
        dy = oy - y
        dz = oz - z
        d_sq = dx * dx + dy * dy + dz * dz
        if d_sq > max_m_sq:
            continue
        if legal_only and not is_legal_jump_destination(sid):
            continue
        out.append((sid, (d_sq ** 0.5) / LY_IN_METERS))
    out.sort(key=lambda t: t[1])
    return out
