"""
Local New Eden coordinate / name / legality table.

Loads system_coords.json (bundled with the app, generated by
tools/gen_system_coords.py) once into memory. Replaces per-system ESI
position/name lookups in the jump-range hot path with pure local reads.
"""
import json
import os
import threading

from app_path import app_dir, bundle_dir

_COORDS_FILENAME = "system_coords.json"

# In-memory tables, built once by _load().
_coords: dict[int, tuple[float, float, float]] = {}   # id -> (x, y, z) meters
_region_of: dict[int, int] = {}                        # id -> region_id
_security_of: dict[int, float] = {}                    # id -> true-sec (full precision)
_name_of: dict[int, str] = {}                          # id -> canonical name
_id_of_name: dict[str, int] = {}                       # lowercased name -> id
_loaded = False
_lock = threading.Lock()


def _data_path() -> str | None:
    """Prefer a writable copy next to the exe, else the bundled read-only copy."""
    p = os.path.join(app_dir(), _COORDS_FILENAME)
    if os.path.exists(p):
        return p
    p = os.path.join(bundle_dir(), _COORDS_FILENAME)
    if os.path.exists(p):
        return p
    return None


def _load() -> None:
    global _loaded
    if _loaded:
        return
    with _lock:
        if _loaded:
            return
        path = _data_path()
        if not path:
            # No table shipped/cached: degrade gracefully -- callers fall back to ESI.
            _loaded = True
            return
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw = json.load(f)
            for sid_str, rec in raw.items():
                sid = int(sid_str)
                _coords[sid] = (rec["x"], rec["y"], rec["z"])
                _region_of[sid] = rec["region_id"]
                _security_of[sid] = rec["security"]
                name = rec["name"]
                _name_of[sid] = name
                _id_of_name[name.lower()] = sid
            print(f"[Coords] Loaded {len(_coords)} systems from {os.path.basename(path)}")
        except Exception as e:  # corrupt/partial file: degrade, don't crash the app
            print(f"[Coords] Failed to load {path}: {e}")
        _loaded = True
